#!/usr/bin/env bash

# USAGE: cronjob-add '*/6 * * * * find $INSTALL_DIR/data -mmin +45 -type f -delete'

set -eu

if [ -f /.dockerenv ]; then
	echo "[NOTICE] There is no crontab inside docker, we'll skip crontabs in testing environments. Crontab would be:"
	echo "  user = root"
	echo "  $1"
	exit 0
fi

( crontab -l; cat - <<EOF ) | crontab -
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SHELL=/bin/sh

$1

EOF
